// ignore_for_file: avoid_print, deprecated_member_use
//
// Vocabify transcript ingestion CLI (v3).
//
// Two modes:
//
//  1) YouTube mode — fetch captions directly from YouTube:
//       dart run tool/ingest_transcript.dart \
//           --id <youtubeVideoId> \
//           --movieId <slug> \
//           --title "Movie Title" \
//           --tags travel,daily \
//           [--lang en] [--list] [--debug]
//
//  2) File mode — ingest a local .vtt / .srt / .ttml subtitle file:
//       dart run tool/ingest_transcript.dart \
//           --file path/to/subs.vtt \
//           --movieId <slug> \
//           --title "Movie Title" \
//           --youtubeId <id> \         # optional — used by the in-app player
//           --tags travel,daily \
//           [--debug]
//
// Output: assets/transcripts/<movieId>.json
//
// Exit codes:
//   0  success
//   64 usage error
//   65 no caption tracks available (YouTube mode)
//   66 no track for requested language (YouTube mode)
//   67 all ingestion strategies failed
//   68 local subtitle file could not be parsed
//   69 local subtitle file not found / unreadable
//   70 network error (YouTube mode)
//   99 unexpected error

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:xml/xml.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';

import '../lib/core/text/lemmatizer.dart';

const _kBucketMaxMs = 10000;
const _kBucketMinMs = 5000;

Future<void> main(List<String> args) async {
  final flags = _parseFlags(args);
  final debug = flags.containsKey('debug');

  if (flags.containsKey('help') || flags.containsKey('h')) {
    _printUsage();
    exit(0);
  }

  final log = _Log(debug);

  try {
    if (flags.containsKey('file')) {
      await _runFileMode(flags, log);
    } else if (flags.containsKey('id')) {
      await _runYoutubeMode(flags, log);
    } else {
      stderr.writeln('error: --id or --file is required');
      _printUsage();
      exit(64);
    }
  } catch (e, st) {
    stderr.writeln('✗ Unexpected error: ${_summarize(e)}');
    if (debug) stderr.writeln(st);
    exit(99);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// YouTube mode
// ─────────────────────────────────────────────────────────────────────────────

Future<void> _runYoutubeMode(Map<String, String> flags, _Log log) async {
  final videoId = flags['id']!;
  final listOnly = flags.containsKey('list');

  if (!listOnly) {
    if (flags['movieId'] == null || flags['title'] == null) {
      stderr.writeln(
          'error: --movieId and --title are required unless --list');
      _printUsage();
      exit(64);
    }
  }

  final lang = flags['lang'] ?? 'en';
  final movieId = flags['movieId'] ?? '';
  final title = flags['title'] ?? '';
  final seriesId = flags['seriesId'];
  final tags = _parseTags(flags['tags']);

  final yt = YoutubeExplode();
  final client = http.Client();

  try {
    log.info('Fetching caption manifest for video "$videoId"…');
    final manifest = await _safeGetManifest(yt, videoId, log);
    if (manifest == null) exit(70);
    if (manifest.tracks.isEmpty) {
      stderr.writeln(
          '✗ No caption tracks available for $videoId. Publish captions or try a different video.');
      exit(65);
    }

    log.info('Available tracks:');
    for (final t in manifest.tracks) {
      log.info('  • lang=${t.language.code} (${t.language.name}) '
          'auto=${t.isAutoGenerated} format=${t.format.formatCode}');
    }

    if (listOnly) exit(0);

    // Build an ordered candidate list of (track, format) pairs to try.
    final candidates = _buildCandidatePairs(manifest, lang);
    if (candidates.isEmpty) {
      stderr.writeln(
          '✗ No tracks matched language "$lang". Run with --list to inspect, then pass --lang <code>.');
      exit(66);
    }

    log.info('Will try ${candidates.length} (track × format) combinations.');

    final errors = <String>[];
    List<_RawCaption>? captions;
    String? usedStrategy;

    for (final pair in candidates) {
      final strategyName =
          '${pair.track.language.code}/${pair.formatOverride ?? "orig(${pair.track.format.formatCode})"}';
      log.info('→ Trying: $strategyName '
          '${pair.track.isAutoGenerated ? "(auto-gen) " : ""}');

      try {
        final result = await _fetchAndParse(
          client: client,
          track: pair.track,
          formatOverride: pair.formatOverride,
          log: log,
        );
        if (result.isNotEmpty) {
          captions = result;
          usedStrategy = strategyName;
          break;
        }
        errors.add('$strategyName: returned 0 captions');
        log.warn('$strategyName: returned 0 captions');
      } catch (e) {
        errors.add('$strategyName: ${_summarize(e)}');
        log.warn('$strategyName: ${_summarize(e)}');
      }
    }

    // Last-resort: let youtube_explode_dart try on its own against the best track.
    if (captions == null || captions.isEmpty) {
      log.info('→ Last resort: youtube_explode_dart default parser');
      final best = candidates.first.track;
      try {
        final tr = await yt.videos.closedCaptions.get(best);
        final out = <_RawCaption>[];
        for (final c in tr.captions) {
          final t = c.text.trim();
          if (t.isEmpty) continue;
          out.add(_RawCaption(
            startMs: c.offset.inMilliseconds,
            endMs: (c.offset + c.duration).inMilliseconds,
            text: t,
          ));
        }
        if (out.isNotEmpty) {
          captions = out;
          usedStrategy = 'youtube_explode_dart/default';
        } else {
          errors.add('youtube_explode_dart/default: 0 captions');
        }
      } catch (e) {
        errors.add('youtube_explode_dart/default: ${_summarize(e)}');
      }
    }

    if (captions == null || captions.isEmpty) {
      stderr.writeln('✗ All YouTube ingestion strategies failed:');
      for (final e in errors) {
        stderr.writeln('  · $e');
      }
      stderr.writeln('\nHints:');
      stderr.writeln(
          '  · Some videos refuse to serve timedtext to non-browser clients.');
      stderr.writeln(
          '  · Download the .vtt/.srt yourself (e.g. yt-dlp --write-sub --sub-lang $lang --skip-download <videoId>),');
      stderr.writeln(
          '    then re-run this tool with --file <path> instead of --id.');
      exit(67);
    }

    _writeOutput(
      movieId: movieId,
      seriesId: seriesId,
      title: title,
      youtubeId: videoId,
      tags: tags,
      captions: captions,
      strategyLabel: usedStrategy ?? 'unknown',
    );
  } finally {
    yt.close();
    client.close();
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// File mode
// ─────────────────────────────────────────────────────────────────────────────

Future<void> _runFileMode(Map<String, String> flags, _Log log) async {
  final path = flags['file']!;
  if (flags['movieId'] == null || flags['title'] == null) {
    stderr.writeln('error: --movieId and --title are required in file mode');
    _printUsage();
    exit(64);
  }

  final movieId = flags['movieId']!;
  final title = flags['title']!;
  final seriesId = flags['seriesId'];
  final tags = _parseTags(flags['tags']);
  final youtubeId = flags['youtubeId'] ?? '';

  final file = File(path);
  if (!file.existsSync()) {
    stderr.writeln('✗ File not found: $path');
    exit(69);
  }

  String raw;
  try {
    raw = file.readAsStringSync();
  } catch (e) {
    stderr.writeln('✗ Failed to read $path: ${_summarize(e)}');
    exit(69);
  }

  final lower = path.toLowerCase();
  List<_RawCaption>? captions;
  String parser;

  try {
    if (lower.endsWith('.vtt') || _looksLikeVtt(raw)) {
      captions = _parseVtt(raw);
      parser = 'vtt';
    } else if (lower.endsWith('.srt') || _looksLikeSrt(raw)) {
      captions = _parseSrt(raw);
      parser = 'srt';
    } else if (lower.endsWith('.ttml') ||
        lower.endsWith('.xml') ||
        _looksLikeTtml(raw)) {
      captions = _parseTtml(raw);
      parser = 'ttml';
    } else {
      stderr.writeln(
          '✗ Unrecognized subtitle format. Supported: .vtt, .srt, .ttml, .xml');
      exit(68);
    }
  } catch (e) {
    stderr.writeln('✗ Failed to parse $path: ${_summarize(e)}');
    exit(68);
  }

  if (captions.isEmpty) {
    stderr.writeln('✗ Parsed $path but found 0 captions.');
    exit(68);
  }

  log.info('Parsed ${captions.length} captions using $parser parser.');

  _writeOutput(
    movieId: movieId,
    seriesId: seriesId,
    title: title,
    youtubeId: youtubeId,
    tags: tags,
    captions: captions,
    strategyLabel: 'file:$parser',
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// YouTube candidate selection
// ─────────────────────────────────────────────────────────────────────────────

class _Candidate {
  _Candidate({required this.track, required this.formatOverride});
  final ClosedCaptionTrackInfo track;

  /// null = use the track URL as-is (no fmt rewrite). Otherwise force
  /// a specific fmt query param: 'srv3', 'vtt', 'ttml', 'json3'.
  final String? formatOverride;
}

/// Produces an ordered candidate list. Order of preference:
///   1. Manual (non-auto) tracks matching the exact lang, trying formats
///      in this order: original URL → srv3 → vtt → ttml → json3.
///   2. Manual tracks matching the language root (e.g. "en" matches "en-GB").
///   3. Auto-generated tracks, same language/format preference.
///   4. First track in the manifest, all formats.
List<_Candidate> _buildCandidatePairs(
    ClosedCaptionManifest manifest, String lang) {
  const formatOrder = <String?>[null, 'srv3', 'vtt', 'ttml', 'json3'];

  bool exactLang(ClosedCaptionTrackInfo t) =>
      t.language.code.toLowerCase() == lang.toLowerCase();

  bool rootLang(ClosedCaptionTrackInfo t) {
    final root = lang.toLowerCase().split('-').first;
    final code = t.language.code.toLowerCase();
    return code == root || code.startsWith('$root-');
  }

  final seen = <String>{};
  final out = <_Candidate>[];

  void addGroup(Iterable<ClosedCaptionTrackInfo> tracks) {
    for (final t in tracks) {
      for (final fmt in formatOrder) {
        final key =
            '${t.url}|${fmt ?? "orig"}|${t.language.code}|${t.isAutoGenerated}';
        if (seen.add(key)) {
          out.add(_Candidate(track: t, formatOverride: fmt));
        }
      }
    }
  }

  // Tier A: manual + exact lang
  addGroup(
    manifest.tracks.where((t) => !t.isAutoGenerated && exactLang(t)),
  );
  // Tier B: manual + root lang
  addGroup(
    manifest.tracks.where((t) => !t.isAutoGenerated && rootLang(t)),
  );
  // Tier C: auto + exact lang
  addGroup(
    manifest.tracks.where((t) => t.isAutoGenerated && exactLang(t)),
  );
  // Tier D: auto + root lang
  addGroup(
    manifest.tracks.where((t) => t.isAutoGenerated && rootLang(t)),
  );
  // Tier E: anything
  if (out.isEmpty) addGroup(manifest.tracks);

  return out;
}

Future<ClosedCaptionManifest?> _safeGetManifest(
    YoutubeExplode yt, String videoId, _Log log) async {
  try {
    return await yt.videos.closedCaptions.getManifest(videoId, formats: const [
      ClosedCaptionFormat.srv3,
      ClosedCaptionFormat.ttml,
      ClosedCaptionFormat.vtt,
    ]);
  } catch (_) {
    try {
      return await yt.videos.closedCaptions.getManifest(videoId);
    } catch (e2) {
      stderr.writeln('✗ Failed to get caption manifest: ${_summarize(e2)}');
      return null;
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Fetch + sniff + parse
// ─────────────────────────────────────────────────────────────────────────────

Future<List<_RawCaption>> _fetchAndParse({
  required http.Client client,
  required ClosedCaptionTrackInfo track,
  required String? formatOverride,
  required _Log log,
}) async {
  final url = formatOverride == null
      ? track.url.toString()
      : _forceFormat(track.url.toString(), formatOverride);

  log.debug('GET $url');

  final resp = await client.get(Uri.parse(url)).timeout(
    const Duration(seconds: 15),
    onTimeout: () {
      throw TimeoutException('timed out after 15s');
    },
  );
  if (resp.statusCode != 200) {
    throw HttpException(
      'HTTP ${resp.statusCode}',
      uri: Uri.parse(url),
    );
  }
  final body = resp.body;
  final trimmed = body.trim();
  if (trimmed.isEmpty) {
    throw const FormatException('response was empty (0 bytes)');
  }

  // Sniff format from body, not from the URL parameter. YouTube sometimes
  // serves one format when we asked for another, or serves nothing when the
  // requested format isn't available for that track.
  if (trimmed.startsWith('<')) {
    // XML family: could be srv3, srv1/srv2, or TTML.
    return _parseXmlTimedText(trimmed);
  } else if (trimmed.startsWith('{')) {
    return _parseJson3(trimmed);
  } else if (_looksLikeVtt(trimmed)) {
    return _parseVtt(trimmed);
  } else {
    throw FormatException(
        'unrecognized body (first bytes: "${_preview(trimmed)}")');
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Parsers
// ─────────────────────────────────────────────────────────────────────────────

List<_RawCaption> _parseXmlTimedText(String body) {
  final doc = XmlDocument.parse(body);
  final out = <_RawCaption>[];

  // srv3: <timedtext><body><p t="..." d="...">...</p></body></timedtext>
  for (final p in doc.findAllElements('p')) {
    final tAttr = p.getAttribute('t');
    if (tAttr == null) continue;
    final startMs = int.tryParse(tAttr) ?? 0;
    final durMs = int.tryParse(p.getAttribute('d') ?? '') ?? 0;
    final endMs = startMs + (durMs > 0 ? durMs : 3000);
    final text = _extractText(p).trim();
    if (text.isEmpty) continue;
    out.add(_RawCaption(startMs: startMs, endMs: endMs, text: text));
  }

  // srv1/srv2: <transcript><text start="..." dur="...">...</text></transcript>
  if (out.isEmpty) {
    for (final t in doc.findAllElements('text')) {
      final startAttr = t.getAttribute('start');
      if (startAttr == null) continue;
      final startSec = double.tryParse(startAttr) ?? 0;
      final durSec = double.tryParse(t.getAttribute('dur') ?? '') ?? 0;
      final startMs = (startSec * 1000).round();
      final endMs =
          ((startSec + (durSec > 0 ? durSec : 3)) * 1000).round();
      final text = _decodeHtml(t.innerText).trim();
      if (text.isEmpty) continue;
      out.add(_RawCaption(startMs: startMs, endMs: endMs, text: text));
    }
  }

  // TTML: <tt><body><div><p begin="00:00:01.000" end="00:00:03.000">...</p>...
  if (out.isEmpty) {
    for (final p in doc.findAllElements('p')) {
      final begin = p.getAttribute('begin');
      final end = p.getAttribute('end');
      final dur = p.getAttribute('dur');
      if (begin == null) continue;
      final startMs = _ttmlTimeToMs(begin);
      final endMs = end != null
          ? _ttmlTimeToMs(end)
          : (dur != null ? startMs + _ttmlTimeToMs(dur) : startMs + 3000);
      final text = _extractText(p).trim();
      if (text.isEmpty) continue;
      out.add(_RawCaption(startMs: startMs, endMs: endMs, text: text));
    }
  }

  return out;
}

List<_RawCaption> _parseJson3(String body) {
  final data = jsonDecode(body) as Map<String, dynamic>;
  final events = (data['events'] as List<dynamic>?) ?? const [];
  final out = <_RawCaption>[];
  for (final e in events) {
    final ev = e as Map<String, dynamic>;
    final startMs = (ev['tStartMs'] as num?)?.toInt();
    final durMs = (ev['dDurationMs'] as num?)?.toInt();
    if (startMs == null) continue;
    final segs = (ev['segs'] as List<dynamic>?) ?? const [];
    final buf = StringBuffer();
    for (final s in segs) {
      final utf8Text = (s as Map<String, dynamic>)['utf8'];
      if (utf8Text is String) buf.write(utf8Text);
    }
    final text = buf.toString().trim();
    if (text.isEmpty) continue;
    final endMs = startMs + (durMs ?? 3000);
    out.add(_RawCaption(startMs: startMs, endMs: endMs, text: text));
  }
  return out;
}

List<_RawCaption> _parseVtt(String body) {
  // WebVTT block format:
  //   00:00:01.000 --> 00:00:03.500 [optional settings]
  //   line 1
  //   line 2 (may span multiple lines until a blank line)
  final lines = body.replaceAll('\r\n', '\n').split('\n');
  final out = <_RawCaption>[];
  final cueRe = RegExp(
    r'^(\d{1,2}:)?(\d{2}):(\d{2})\.(\d{3})\s*-->\s*(\d{1,2}:)?(\d{2}):(\d{2})\.(\d{3})',
  );

  for (var i = 0; i < lines.length; i++) {
    final line = lines[i];
    final m = cueRe.firstMatch(line);
    if (m == null) continue;

    int toMs(String? h, String mm, String ss, String ms) {
      final hours = int.parse((h ?? '0:').replaceAll(':', ''));
      final mins = int.parse(mm);
      final secs = int.parse(ss);
      final millis = int.parse(ms);
      return (((hours * 60) + mins) * 60 + secs) * 1000 + millis;
    }

    final startMs = toMs(m.group(1), m.group(2)!, m.group(3)!, m.group(4)!);
    final endMs = toMs(m.group(5), m.group(6)!, m.group(7)!, m.group(8)!);

    // Read text lines until blank
    final textBuf = <String>[];
    var j = i + 1;
    while (j < lines.length && lines[j].trim().isNotEmpty) {
      textBuf.add(_stripVttTags(lines[j]));
      j++;
    }
    i = j;

    final text = textBuf.join(' ').replaceAll(RegExp(r'\s+'), ' ').trim();
    if (text.isEmpty) continue;
    out.add(_RawCaption(startMs: startMs, endMs: endMs, text: text));
  }
  return out;
}

String _stripVttTags(String line) {
  // Remove VTT inline tags like <c.color>, <v Speaker>, <00:00:05.000>.
  return line.replaceAll(RegExp(r'<[^>]+>'), '');
}

List<_RawCaption> _parseSrt(String body) {
  final normalized = body.replaceAll('\r\n', '\n');
  // Blocks are separated by blank lines.
  final blocks = normalized.split(RegExp(r'\n{2,}'));
  final timeRe = RegExp(
    r'(\d{2}):(\d{2}):(\d{2})[,.](\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2})[,.](\d{3})',
  );
  final out = <_RawCaption>[];
  for (final block in blocks) {
    final lines = block
        .split('\n')
        .map((l) => l.trim())
        .where((l) => l.isNotEmpty)
        .toList();
    if (lines.isEmpty) continue;

    // The index line is optional-ish; find the timestamp line.
    String? timeLine;
    var textStart = 0;
    for (var i = 0; i < lines.length; i++) {
      if (timeRe.hasMatch(lines[i])) {
        timeLine = lines[i];
        textStart = i + 1;
        break;
      }
    }
    if (timeLine == null) continue;
    final m = timeRe.firstMatch(timeLine)!;
    int toMs(int h, int mm, int ss, int ms) =>
        (((h * 60) + mm) * 60 + ss) * 1000 + ms;
    final startMs = toMs(
      int.parse(m.group(1)!),
      int.parse(m.group(2)!),
      int.parse(m.group(3)!),
      int.parse(m.group(4)!),
    );
    final endMs = toMs(
      int.parse(m.group(5)!),
      int.parse(m.group(6)!),
      int.parse(m.group(7)!),
      int.parse(m.group(8)!),
    );
    final text = lines
        .sublist(textStart)
        .join(' ')
        .replaceAll(RegExp(r'<[^>]+>'), '')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
    if (text.isEmpty) continue;
    out.add(_RawCaption(startMs: startMs, endMs: endMs, text: text));
  }
  return out;
}

List<_RawCaption> _parseTtml(String body) {
  final doc = XmlDocument.parse(body);
  final out = <_RawCaption>[];
  for (final p in doc.findAllElements('p')) {
    final begin = p.getAttribute('begin');
    if (begin == null) continue;
    final startMs = _ttmlTimeToMs(begin);
    final end = p.getAttribute('end');
    final dur = p.getAttribute('dur');
    final endMs = end != null
        ? _ttmlTimeToMs(end)
        : (dur != null ? startMs + _ttmlTimeToMs(dur) : startMs + 3000);
    final text = _extractText(p).trim();
    if (text.isEmpty) continue;
    out.add(_RawCaption(startMs: startMs, endMs: endMs, text: text));
  }
  return out;
}

/// Parses TTML timestamp strings: "HH:MM:SS.mmm", "SS.mmms", "SSs", or plain ms.
int _ttmlTimeToMs(String s) {
  final clock =
      RegExp(r'^(\d{1,2}):(\d{2}):(\d{2})(?:\.(\d{1,3}))?$').firstMatch(s);
  if (clock != null) {
    final h = int.parse(clock.group(1)!);
    final m = int.parse(clock.group(2)!);
    final sec = int.parse(clock.group(3)!);
    final ms = int.parse((clock.group(4) ?? '0').padRight(3, '0'));
    return (((h * 60) + m) * 60 + sec) * 1000 + ms;
  }
  final seconds = RegExp(r'^([\d.]+)s$').firstMatch(s);
  if (seconds != null) {
    return (double.parse(seconds.group(1)!) * 1000).round();
  }
  return int.tryParse(s) ?? 0;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

class _RawCaption {
  _RawCaption({required this.startMs, required this.endMs, required this.text});
  final int startMs;
  final int endMs;
  final String text;
}

void _writeOutput({
  required String movieId,
  String? seriesId,
  required String title,
  required String youtubeId,
  required List<String> tags,
  required List<_RawCaption> captions,
  required String strategyLabel,
}) {
  final segments = _bucketize(captions);
  if (segments.isEmpty) {
    stderr.writeln('✗ Captions parsed but bucketing produced 0 segments.');
    exit(67);
  }

  final out = <String, dynamic>{
    'movieId': movieId,
    if (seriesId != null) 'seriesId': seriesId,
    'movieTitle': title,
    'youtubeVideoId': youtubeId,
    'topicTags': tags,
    'segments': segments,
  };

  final dir = Directory('assets/transcripts');
  if (!dir.existsSync()) dir.createSync(recursive: true);
  final file = File('assets/transcripts/$movieId.json');
  file.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(out));

  print('✓ Wrote ${segments.length} segments via "$strategyLabel"');
  print('  → ${file.path}');
  if (youtubeId.isEmpty) {
    print('  ! youtubeVideoId is empty; edit the JSON to set one');
    print('    before the app can stream playback for these scenes.');
  }
  print('  → Remember to add this path to `transcriptManifest` in');
  print('    lib/features/subtitle_scene/data/transcript_corpus.dart');
  exit(0);
}

List<Map<String, dynamic>> _bucketize(List<_RawCaption> captions) {
  captions.sort((a, b) => a.startMs.compareTo(b.startMs));
  final segments = <Map<String, dynamic>>[];
  var bucketStart = 0;
  var bucketEnd = 0;
  final bucketText = <String>[];

  void flush() {
    if (bucketText.isEmpty) return;
    final text =
        bucketText.join(' ').replaceAll(RegExp(r'\s+'), ' ').trim();
    if (text.isEmpty) {
      bucketText.clear();
      return;
    }
    final lemmas = Lemmatizer.lemmatize(text);
    segments.add({
      'startMs': bucketStart,
      'endMs': bucketEnd,
      'text': text,
      'lemmas': lemmas,
    });
    bucketText.clear();
  }

  for (final c in captions) {
    if (bucketText.isEmpty) {
      bucketStart = c.startMs;
      bucketEnd = c.endMs;
      bucketText.add(c.text);
      continue;
    }
    final proposedDur = c.endMs - bucketStart;
    if (proposedDur <= _kBucketMaxMs) {
      bucketEnd = c.endMs;
      bucketText.add(c.text);
    } else {
      flush();
      bucketStart = c.startMs;
      bucketEnd = c.endMs;
      bucketText.add(c.text);
    }
    if ((bucketEnd - bucketStart) >= _kBucketMinMs &&
        bucketText.length >= 2) {
      flush();
    }
  }
  flush();
  return segments;
}

String _extractText(XmlElement p) {
  final buf = StringBuffer();
  for (final node in p.descendants) {
    if (node is XmlText) buf.write(node.value);
  }
  return _decodeHtml(buf.toString()).replaceAll(RegExp(r'\s+'), ' ');
}

String _decodeHtml(String s) {
  return s
      .replaceAll('&amp;', '&')
      .replaceAll('&lt;', '<')
      .replaceAll('&gt;', '>')
      .replaceAll('&quot;', '"')
      .replaceAll('&#39;', "'")
      .replaceAll('&nbsp;', ' ');
}

String _forceFormat(String url, String fmt) {
  final uri = Uri.parse(url);
  final qp = Map<String, String>.from(uri.queryParameters);
  qp['fmt'] = fmt;
  return uri.replace(queryParameters: qp).toString();
}

bool _looksLikeVtt(String body) {
  final t = body.trimLeft();
  return t.startsWith('WEBVTT') || RegExp(r'^\ufeff?WEBVTT').hasMatch(t);
}

bool _looksLikeSrt(String body) {
  // SRT blocks: "1\n00:00:01,000 --> 00:00:02,000\nText"
  return RegExp(
    r'^\s*\d+\s*\n\s*\d{2}:\d{2}:\d{2}[,.]\d{3}\s*-->',
    multiLine: true,
  ).hasMatch(body);
}

bool _looksLikeTtml(String body) {
  final t = body.trimLeft();
  return t.startsWith('<') &&
      (t.contains('<tt ') ||
          t.contains('<tt>') ||
          t.contains('xmlns="http://www.w3.org/ns/ttml"'));
}

List<String> _parseTags(String? raw) => (raw ?? '')
    .split(',')
    .map((s) => s.trim())
    .where((s) => s.isNotEmpty)
    .toList();

String _preview(String s) {
  final firstLine = s.split('\n').first;
  final t =
      firstLine.length > 120 ? '${firstLine.substring(0, 120)}…' : firstLine;
  return t.replaceAll('"', r'\"');
}

String _summarize(Object e) {
  final s = e.toString();
  return s.length <= 300 ? s : '${s.substring(0, 300)}…';
}

Map<String, String> _parseFlags(List<String> args) {
  final out = <String, String>{};
  for (var i = 0; i < args.length; i++) {
    final a = args[i];
    if (!a.startsWith('--')) continue;
    final key = a.substring(2);
    if (i + 1 >= args.length || args[i + 1].startsWith('--')) {
      out[key] = '';
      continue;
    }
    out[key] = args[++i];
  }
  return out;
}

void _printUsage() {
  stderr.writeln('''
Usage:

  YouTube mode:
    dart run tool/ingest_transcript.dart --id <videoId> --movieId <slug>
                                         --title "<t>" [--tags a,b]
                                         [--lang en] [--list] [--debug]

  File mode (vtt/srt/ttml):
    dart run tool/ingest_transcript.dart --file <path> --movieId <slug>
                                         --title "<t>" [--youtubeId <id>]
                                         [--tags a,b] [--debug]

Output: assets/transcripts/<movieId>.json

Exit codes:
  0 ok | 64 usage | 65 no tracks | 66 lang missing
  67 all YouTube strategies failed | 68 file parse failed
  69 file not found | 70 network | 99 unexpected
''');
}

class _Log {
  _Log(this.debugMode);
  final bool debugMode;
  void info(String msg) => print('  $msg');
  void warn(String msg) => print('  ! $msg');
  void debug(String msg) {
    if (debugMode) print('  · $msg');
  }
}